/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//changes/(index)'
      | '//changes/[id]'
      | '//changes/create'
      | '//changes/edit/[changeId]'
      | '//epics/(index)'
      | '//epics/create'
      | '//epics/edit/[id]'
      | '//help'
      | '//loading'
      | '//planning'
      | '//projects'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//changes/(index)': RouteRecordInfo<
      '//changes/(index)',
      '/changes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//changes/[id]': RouteRecordInfo<
      '//changes/[id]',
      '/changes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '//changes/create': RouteRecordInfo<
      '//changes/create',
      '/changes/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//changes/edit/[changeId]': RouteRecordInfo<
      '//changes/edit/[changeId]',
      '/changes/edit/:changeId',
      { changeId: ParamValue<true> },
      { changeId: ParamValue<false> },
      | never
    >,
    '//epics/(index)': RouteRecordInfo<
      '//epics/(index)',
      '/epics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//epics/create': RouteRecordInfo<
      '//epics/create',
      '/epics/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//epics/edit/[id]': RouteRecordInfo<
      '//epics/edit/[id]',
      '/epics/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '//help': RouteRecordInfo<
      '//help',
      '/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//loading': RouteRecordInfo<
      '//loading',
      '/loading',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//planning': RouteRecordInfo<
      '//planning',
      '/planning',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//projects': RouteRecordInfo<
      '//projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//changes/(index)'
        | '//changes/[id]'
        | '//changes/create'
        | '//changes/edit/[changeId]'
        | '//epics/(index)'
        | '//epics/create'
        | '//epics/edit/[id]'
        | '//help'
        | '//loading'
        | '//planning'
        | '//projects'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/changes/(index).vue': {
      routes:
        | '//changes/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/changes/[id].vue': {
      routes:
        | '//changes/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/index/changes/create.vue': {
      routes:
        | '//changes/create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/changes/edit/[changeId].vue': {
      routes:
        | '//changes/edit/[changeId]'
      views:
        | never
      pathParamNames:
        | 'changeId'
    }
    'src/pages/index/epics/(index).vue': {
      routes:
        | '//epics/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/epics/create.vue': {
      routes:
        | '//epics/create'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/epics/edit/[id].vue': {
      routes:
        | '//epics/edit/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/index/help.vue': {
      routes:
        | '//help'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/loading.vue': {
      routes:
        | '//loading'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/planning.vue': {
      routes:
        | '//planning'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/projects.vue': {
      routes:
        | '//projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
