/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//help'
      | '//loading'
      | '//planning'
      | '//projects'
      | '//tasks/(index)'
      | '//tasks/[id]'
      | '//tasks/create/[parentId]'
      | '//tasks/edit/[taskId]'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//help': RouteRecordInfo<
      '//help',
      '/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//loading': RouteRecordInfo<
      '//loading',
      '/loading',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//planning': RouteRecordInfo<
      '//planning',
      '/planning',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//projects': RouteRecordInfo<
      '//projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//tasks/(index)': RouteRecordInfo<
      '//tasks/(index)',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//tasks/[id]': RouteRecordInfo<
      '//tasks/[id]',
      '/tasks/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '//tasks/create/[parentId]': RouteRecordInfo<
      '//tasks/create/[parentId]',
      '/tasks/create/:parentId',
      { parentId: ParamValue<true> },
      { parentId: ParamValue<false> },
      | never
    >,
    '//tasks/edit/[taskId]': RouteRecordInfo<
      '//tasks/edit/[taskId]',
      '/tasks/edit/:taskId',
      { taskId: ParamValue<true> },
      { taskId: ParamValue<false> },
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//help'
        | '//loading'
        | '//planning'
        | '//projects'
        | '//tasks/(index)'
        | '//tasks/[id]'
        | '//tasks/create/[parentId]'
        | '//tasks/edit/[taskId]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/help.vue': {
      routes:
        | '//help'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/loading.vue': {
      routes:
        | '//loading'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/planning.vue': {
      routes:
        | '//planning'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/projects.vue': {
      routes:
        | '//projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/tasks/(index).vue': {
      routes:
        | '//tasks/(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/tasks/[id].vue': {
      routes:
        | '//tasks/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/index/tasks/create/[parentId].vue': {
      routes:
        | '//tasks/create/[parentId]'
      views:
        | never
      pathParamNames:
        | 'parentId'
    }
    'src/pages/index/tasks/edit/[taskId].vue': {
      routes:
        | '//tasks/edit/[taskId]'
      views:
        | never
      pathParamNames:
        | 'taskId'
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
