drop procedure if exists public.sp_requirement_to_history;
drop procedure if exists public.sp_change_to_history;
drop procedure if exists public.sp_change_requirement_recalculate;

drop view if exists public.vw_change;
drop view if exists public.vw_project;

drop table if exists public.change;
drop table if exists public.chage_history;
drop table if exists public.change_phase;
drop table if exists public.change_type;
drop table if exists public.epic;
drop table if exists public.epic_history;
drop table if exists public.project;
drop table if exists public.requirement_history;
drop table if exists public.requirement;

create table project
(
    id       bigint generated by default as identity
        primary key,
    name     text                                   not null,
    created  timestamp with time zone default now() not null,
    modified timestamp with time zone default now() not null
);

create table requirement
(
    id         bigint generated by default as identity
        primary key,
    version    smallint                 default 0     not null,
    definition text                                   not null,
    done       boolean                  default false not null,
    change_id  bigint                                 not null,
    created    timestamp with time zone default now() not null,
    modified   timestamp with time zone default now() not null
);

create table requirement_history
(
    id         bigint                   not null,
    version    smallint                 not null,
    definition text                     not null,
    modified   timestamp with time zone not null,
    deleted    boolean                  not null,
    primary key (id, version)
);

create table change_phase
(
    slug     text    default 'backlog'::text not null
        constraint task_phase_pkey
            primary key,
    priority integer default 0               not null
);

create table change_type
(
    slug     text    default 'task'::text not null
        constraint task_type_pkey
            primary key,
    priority integer default 0            not null
);

create table change
(
    id           bigint generated by default as identity
        constraint task_pkey
            primary key,
    version      smallint                 default 0               not null,
    project_id   bigint                                           not null,
    epic_id      bigint,
    change_phase text                     default 'backlog'::text not null,
    change_types text[]                                           not null,
    title        text                                             not null,
    body         text,
    closed       boolean                  default false           not null,
    done_req     smallint                 default 0               not null,
    total_req    smallint                 default 0               not null,
    completed    smallint generated always as (COALESCE(((done_req / NULLIF(total_req, 0)))::integer, 0)) virtual,
    created      timestamp with time zone default now()           not null,
    modified     timestamp with time zone default now()           not null
);

create table change_history
(
    id           bigint                   not null,
    version      smallint                 not null,
    project_id   bigint                   not null,
    epic_id      bigint                   not null,
    change_types text[]                   not null,
    title        text                     not null,
    body         text,
    modified     timestamp with time zone not null,
    deleted      boolean default false    not null,
    constraint task_history_pkey
        primary key (id, version)
);

create table epic_history
(
    id       bigint                   not null,
    version  smallint                 not null,
    name     text                     not null,
    modified timestamp with time zone not null,
    deleted  boolean default false    not null,
    primary key (id, version)
);

create table epic
(
    id        bigint generated by default as identity
        primary key,
    version   smallint                               not null,
    name      text                                   not null,
    done_req  smallint                 default 0     not null,
    total_req smallint                 default 0     not null,
    completed smallint generated always as (COALESCE(((done_req / NULLIF(total_req, 0)))::integer, 0)) virtual,
    created   timestamp with time zone default now() not null,
    modified  timestamp with time zone default now() not null
);

create view vw_change
as
SELECT id,
       version,
       project_id,
       epic_id,
       change_phase,
       change_types,
       title,
       body,
       closed,
       done_req,
       total_req,
       COALESCE((done_req / NULLIF(total_req, 0))::integer, 0) AS completed,
       created,
       modified
FROM change;

create view public.vw_project as
SELECT p.id,
       p.name,
       p.created,
       p.modified,
       coalesce(count(t.*), 0) AS change_count
FROM project p
         LEFT JOIN change t ON p.id = t.project_id
GROUP BY p.id, p.name, p.created, p.modified
ORDER BY p.id;

create procedure sp_requirement_to_history(IN _id bigint, IN _deleted boolean)
    language plpgsql
as
$$
begin
    insert into public.requirement_history (id, version, definition, modified, deleted)
    select id,
           version,
           definition,
           modified,
           _deleted
    from public.requirement
    where id = _id;
end;
$$;

create procedure sp_change_requirement_recalculate(IN _change_id bigint)
    language plpgsql
as
$$
declare
    _epic_id bigint;
    _done_req smallint;
    _total_req smallint;
begin
    loop
        select count(*) into _done_req from requirement where change_id=_change_id and done=true;
        select count(*) into _total_req from requirement where change_id=_change_id;

        update public.change
        set
            done_req=_done_req,
            total_req=_total_req
        where id=_change_id;

        select epic_id into _epic_id from change where id=_change_id;
        select
            coalesce(sum(done_req), 0),
            coalesce(sum(total_req), 0)
        into
            _done_req,
            _total_req
        from public.change
        where epic_id=_epic_id;

        update public.epic
        set
            done_req=_done_req,
            total_req=_total_req
        where id=_epic_id;
    end loop;
end;
$$;

create procedure sp_change_to_history(IN _id bigint, IN _deleted boolean)
    language plpgsql
as
$$
begin
    insert into public.change_history (
        id, version, project_id, epic_id, change_types, title, body, modified, deleted
    )
    select
        id, version, project_id, epic_id, change_types, title, body, modified, _deleted
    from public.change
    where id = _id;
end;
$$;
