drop function if exists public.fn_change_insert;
drop function if exists public.fn_change_start_run;
drop function if exists public.fn_change_reset_claim;
drop function if exists public.fn_change_update_run;
drop procedure if exists public.sp_change_assign_flow;
drop procedure if exists public.sp_change_ref_update;
drop procedure if exists public.sp_change_title_update;
drop procedure if exists public.sp_change_idea_update;
drop procedure if exists public.sp_change_spec_update;
drop procedure if exists public.sp_change_pr_update;
drop procedure if exists public.sp_change_ref;
drop procedure if exists public.sp_epic_to_history;
drop procedure if exists public.sp_change_to_history;
drop procedure if exists public.sp_requirement_to_history;
drop procedure if exists public.sp_change_requirement_recalculate;
drop procedure if exists public.sp_epic_requirement_recalculate;
drop procedure if exists public.sp_test_case_to_history;
drop procedure if exists public.sp_change_test_case_recalculate;
drop procedure if exists public.sp_epic_test_case_recalculate;

drop view if exists public.vw_foreign_key;
drop view if exists public.vw_project;
drop view if exists public.vw_epic;
drop view if exists public.vw_change;
drop view if exists public.vw_change_list;
drop view if exists public.vw_change_details;

drop table if exists public.requirement_history cascade;
drop table if exists public.requirement cascade;
drop table if exists public.test_case;
drop table if exists public.test_case_history;
drop table if exists public.change_history cascade;
drop table if exists public.change cascade;
drop table if exists public.change_phase cascade;
drop table if exists public.change_type cascade;
drop table if exists public.epic_history cascade;
drop table if exists public.epic cascade;
drop table if exists public.project cascade;
drop table if exists public.config cascade;

create table public.config
(
    slug                     text   default 'default'::text primary key not null,
    flow_stages              text[]                                     not null,
    flow_stages_help         text[]                                     not null,
    flow_stage_modes_default text[]                                     not null,
    flow_stage_entry_scripts text[]                                     not null,
    flow_stage_prompts       text[]                                     not null,
    flow_stage_exit_scripts  text[]                                     not null,
    stage_modes              text[]                                     not null,
    stage_modes_help         text[]                                     not null,
    task_statuses            text[]                                     not null,
    task_statuses_help       text[]                                     not null,
    task_steps               text[]                                     not null,
    task_steps_help          text[]                                     not null,
    change_phases            text[]                                     not null,
    change_types             text[]                                     not null,
    change_docs              text[]                                     not null
);

create table public.project
(
    id       bigint generated by default as identity primary key not null,
    name     text                                   not null,
    last_ref int                      default 0     not null,
    created  timestamp with time zone default now() not null,
    modified timestamp with time zone default now() not null
);

create table public.epic
(
    id         bigint generated by default as identity primary key not null,
    version    smallint                 default 0     not null,
    project_id bigint                                 not null,
    name       text                                   not null,
    done_tc    smallint                 default 0     not null,
    total_tc   smallint                 default 0     not null,
    completed         smallint generated always as
        (coalesce((100 * done_tc / nullif(total_tc, 0))::smallint, 0)) stored,
    created    timestamp with time zone default now() not null,
    modified   timestamp with time zone default now() not null
);

create table public.epic_history
(
    id         bigint                   not null,
    version    smallint                 not null,
    project_id bigint                   not null,
    name       text                     not null,
    modified   timestamp with time zone not null,
    deleted    boolean default false    not null,
    primary key (id, version)
);

create table public.change_phase
(
    slug     text    default 'backlog' not null primary key,
    priority integer default 0         not null
);

create table public.change_type
(
    slug     text    default 'feature' not null primary key,
    priority integer default 0         not null
);

create table public.change
(
    id               bigint generated by default as identity
        primary key,
    version          smallint                 default 0                 not null,
    ref_uuid         uuid                     default gen_random_uuid() not null,
    ref              integer,
    slug             text,
    project_id       bigint                                             not null,
    change_phase     text                     default 'backlog'::text   not null,
    change_types     text[]                   default ARRAY []::text[]  not null,
    epic_id          bigint,
    title            text                     default ''::text          not null,
    idea             text                     default ''::text          not null,
    spec             text                     default ''::text          not null,
    pr               text                     default ''::text          not null,
    pr_url           text                     default ''::text          not null,
    agent_edit       boolean                  default false             not null,
    flow_stages      text[]                   default ARRAY []::text[]  not null,
    flow_stage_modes text[]                   default ARRAY []::text[]  not null,
    run_claim_id     uuid,
    run_flow_stage   text                     default ''::text          not null,
    run_task_step    text                     default ''::text          not null,
    run_task_status  text                     default ''::text          not null,
    run_error        text                     default ''::text          not null,
    run_is_completed boolean                  default false             not null,
    run_started_at   timestamp with time zone,
    run_updated_at   timestamp with time zone,
    open             boolean                  default true              not null,
    done_tc          smallint                 default 0                 not null,
    total_tc         smallint                 default 0                 not null,
    completed        smallint generated always as (COALESCE(
            ((((100 * done_tc) / NULLIF(total_tc, 0)))::smallint)::integer, 0)) stored,
    created          timestamp with time zone default now()             not null,
    modified         timestamp with time zone default now()             not null
);

create unique index change_ref_uuid_index
    on public.change (ref_uuid);

create table public.change_history
(
    id           bigint                   not null,
    version      smallint                 not null,
    doc_type     text                     not null,
    body         text                     not null,
    agent_edit   boolean                  not null,
    modified     timestamp with time zone not null,
    deleted      boolean default false    not null,
    primary key (id, version)
);

create table public.test_case
(
    id         bigint generated by default as identity
        primary key,
    version    smallint                 default 0     not null,
    change_id  bigint                                 not null,
    scenario   text                                   not null,
    done       boolean                  default false not null,
    created    timestamp with time zone default now() not null,
    modified   timestamp with time zone default now() not null
);

create table public.test_case_history
(
    id         bigint                   not null,
    version    smallint                 not null,
    change_id  bigint                                 not null,
    scenario text                     not null,
    modified   timestamp with time zone not null,
    deleted    boolean                  not null,
    primary key (id, version)
);

create view public.vw_project as
SELECT p.id,
       p.name,
       p.last_ref,
       p.created,
       p.modified,
       COALESCE(count(c.*), 0::bigint) AS change_count
FROM project p
         LEFT JOIN change c ON p.id = c.project_id
GROUP BY p.id, p.name, p.last_ref, p.created, p.modified
ORDER BY p.modified desc;

create view public.vw_epic as
SELECT e.id,
       e.version,
       e.project_id,
       e.name,
       e.done_tc,
       e.total_tc,
       e.completed,
       count(c.*)::integer AS change_count,
       e.created,
       e.modified
FROM epic e
         LEFT JOIN change c ON e.id = c.epic_id
GROUP BY e.id, e.version, e.project_id, e.name, e.done_tc, e.total_tc, e.completed, e.created, e.modified
ORDER BY e.project_id, e.name;

create view public.vw_change_list
as
SELECT c.id,
       c.ref_uuid,
       c.ref,
       c.slug,
       c.project_id,
       c.change_phase,
       c.change_types,
       c.epic_id,
       e.name AS epic_name,
       c.title,
       c.agent_edit,
       c.open,
       c.done_tc,
       c.total_tc,
       c.completed,
       c.modified
FROM change c
         LEFT JOIN epic e ON c.epic_id = e.id
ORDER BY c.project_id, c.modified DESC;

create view public.vw_change_details
as
SELECT c.id,
       c.ref_uuid,
       c.ref,
       c.version,
       c.slug,
       c.project_id,
       c.change_phase,
       c.change_types,
       c.epic_id,
       e.name AS epic_name,
       c.title,
       c.idea,
       c.spec,
       c.pr,
       c.pr_url,
       c.agent_edit,
       c.flow_stages,
       c.flow_stage_modes,
       c.run_claim_id,
       c.run_flow_stage,
       c.run_task_step,
       c.run_task_status,
       c.run_error,
       c.run_is_completed,
       c.run_started_at,
       c.run_updated_at,
       c.open,
       c.done_tc,
       c.total_tc,
       c.completed,
       c.created,
       c.modified
FROM change c
         LEFT JOIN epic e ON c.epic_id = e.id
ORDER BY c.project_id, c.modified DESC;

create view public.vw_foreign_key as
SELECT conname             AS foreign_key_name,
       conrelid::regclass  AS table_name,
       confrelid::regclass AS referenced_table
FROM pg_constraint
WHERE contype = 'f'::"char"
  AND connamespace = 'public'::regnamespace::oid
ORDER BY (conrelid::regclass), conname;

create procedure public.sp_epic_to_history(IN _id bigint, IN _deleted boolean)
    language plpgsql
as
$$
begin
    insert into public.epic_history (
        id, version, project_id, name, modified, deleted
    )
    select
        id, version, project_id, name, modified, _deleted
    from public.epic
    where id = _id;
end;
$$;

create procedure public.sp_test_case_to_history(IN _id bigint, IN _deleted boolean)
    language plpgsql
as
$$
begin
    insert into public.test_case_history (
        id, version, change_id, scenario, modified, deleted
    )
    select
        id, version, change_id, scenario, modified, _deleted
    from public.test_case
    where id = _id;
end;
$$;

create procedure public.sp_epic_test_case_recalculate(IN _epic_id bigint)
    language plpgsql
as
$$
declare
    _done_tc smallint;
    _total_tc smallint;
begin
    if _epic_id is null then return; end if;

    select
        coalesce(sum(done_tc), 0),
        coalesce(sum(total_tc), 0)
    into
        _done_tc,
        _total_tc
    from public.change
    where epic_id=_epic_id;

    update public.epic
    set
        done_tc=_done_tc,
        total_tc=_total_tc
    where id=_epic_id;
end;
$$;

create procedure public.sp_change_test_case_recalculate(IN _change_id bigint)
    language plpgsql
as
$$
declare
    _epic_id bigint;
    _done_tc smallint;
    _total_tc smallint;
begin
    select count(*) into _done_tc from test_case where change_id=_change_id and done=true;
    select count(*) into _total_tc from test_case where change_id=_change_id;

    update public.change
    set
        done_tc=_done_tc,
        total_tc=_total_tc,
        modified=now()
    where id=_change_id;

    select epic_id into _epic_id from change where id=_change_id;
    call sp_epic_test_case_recalculate(_epic_id);
end;
$$;

create function public.fn_change_insert(_project_id bigint, _title text, _idea text) returns bigint
    language plpgsql
as
$$
declare
    _id bigint;
    _agent_edit bool;
    _modified timestamptz;
begin
    insert into public.change (
        project_id, title, idea
    ) values (
        _project_id, _title, _idea
    ) returning id, agent_edit, modified into _id, _agent_edit, _modified;

    insert into public.change_history (
        id, version, doc_type, body, agent_edit, modified
    ) values (
        _id, 0, 'idea', _idea, false, _modified
    );

    return _id;
end;
$$;



create procedure public.sp_change_idea_update(_id bigint, _idea text, _agent_edit bool)
    language plpgsql
as
$$
declare
    _version  smallint;
    _modified timestamptz;
begin
    update public.change
    set version=version+1, idea=_idea, agent_edit=_agent_edit, modified=now()
    where id=_id
    returning version, modified into _version, _modified;

    insert into public.change_history (
        id, version, doc_type, body, agent_edit, modified
    ) values (
        _id, _version, 'idea', _idea, _agent_edit, _modified
    );
end;
$$;



create procedure public.sp_change_spec_update(_id bigint, _spec text, _agent_edit bool)
    language plpgsql
as
$$
declare
    _version  smallint;
    _modified timestamptz;
begin
    update public.change
    set version=version+1, spec=_spec, agent_edit=_agent_edit, modified=now()
    where id=_id
    returning version, modified into _version, _modified;

    insert into public.change_history (
        id, version, doc_type, body, agent_edit, modified
    ) values (
        _id, _version, 'spec', _spec, _agent_edit, _modified
    );
end;
$$;



create procedure public.sp_change_pr_update(_id bigint, _pr text, _agent_edit bool)
    language plpgsql
as
$$
declare
    _version  smallint;
    _modified timestamptz;
begin
    update public.change
    set version=version+1, pr=_pr, agent_edit=_agent_edit, modified=now()
    where id=_id
    returning version, modified into _version, _modified;

    insert into public.change_history (
        id, version, doc_type, body, agent_edit, modified
    ) values (
        _id, _version, 'pr', _pr, _agent_edit, _modified
    );
end;
$$;



create procedure public.sp_change_title_update(_change_id bigint, _title text)
    language plpgsql
as
$$
begin
    update public.change
    set title=regexp_replace(trim(_title), '\s+', ' ', 'g')
    where id=_change_id;
end;
$$;



create procedure public.sp_change_assign_flow(_id bigint)
    language plpgsql
as
$$
declare
    _project_id bigint;
    _ref int;
    _slug text;
    _title text;
    _flow_stages text[];
    _flow_stage_modes text[];
begin
    select project_id, ref, slug, title into _project_id, _ref, _slug, _title from change where id=_id for update;

    if _ref is null then
        select flow_stages, flow_stage_modes_default into _flow_stages, _flow_stage_modes from config where slug='default';
        update public.project set last_ref=last_ref+1 where id=_project_id returning last_ref into _ref;
        update public.change set flow_stages=_flow_stages, flow_stage_modes=_flow_stage_modes where id=_id;
    end if;

    _slug=regexp_replace(lower(trim(_title)), '[^a-z0-9]+', '-', 'g');
    _slug=trim(both '-' from _slug);
    if _slug = '' then
        _slug='change';
    end if;
    _slug=concat(lpad(_ref::text, 3, '0'), '-', _slug);

    update public.change
    set ref=_ref, slug=_slug
    where id=_id;
end;
$$;



create function public.fn_change_start_run(_id bigint)
    returns uuid
    language plpgsql
as
$$
declare
    _claim_id uuid;
begin
    update public.change
    set
        run_claim_id=gen_random_uuid(),
        run_started_at=now()
    where
        id=_id and run_claim_id is null
    returning change.run_claim_id
        into _claim_id;

    return _claim_id;
end;
$$;



create function public.fn_change_update_run(_id bigint, _claim_id uuid, _flow_stage text, _task_step text, _task_status text, _run_error text, _run_is_completed bool)
    returns bigint
    language plpgsql
as
$$
declare
    _return_id bigint;
begin
    if _run_is_completed then
        update public.change
        set
            run_claim_id=null,
            run_flow_stage=_flow_stage,
            run_task_step=_task_step,
            run_task_status=_task_status,
            run_error=_run_error,
            run_is_completed=true,
            run_updated_at=now()
        where id=_id and run_claim_id=_claim_id
        returning id
            into _return_id;
    else
        update public.change
        set
            run_flow_stage=_flow_stage,
            run_task_step=_task_step,
            run_task_status=_task_status,
            run_error=_run_error,
            run_is_completed=false,
            run_updated_at=now()
        where id=_id and run_claim_id=_claim_id
        returning id
            into _return_id;
    end if;

    return _return_id;
end;
$$;



create function public.fn_change_reset_claim(_id bigint)
    returns uuid
    language plpgsql
as
$$
declare
    _claim_id uuid;
begin
    update public.change
    set
        run_claim_id=gen_random_uuid()
    where
        id=_id
    returning run_claim_id
        into _claim_id;

    return _claim_id;
end;
$$;
