drop function if exists public.fn_change_insert;
drop procedure if exists public.sp_epic_to_history;
drop procedure if exists public.sp_change_to_history;
drop procedure if exists public.sp_requirement_to_history;
drop procedure if exists public.sp_change_requirement_recalculate;
drop procedure if exists public.sp_epic_requirement_recalculate;
drop procedure if exists public.sp_test_case_to_history;
drop procedure if exists public.sp_change_test_case_recalculate;
drop procedure if exists public.sp_epic_test_case_recalculate;

drop view if exists public.vw_foreign_key;
drop view if exists public.vw_project;
drop view if exists public.vw_epic;
drop view if exists public.vw_change;

drop table if exists public.requirement_history cascade;
drop table if exists public.requirement cascade;
drop table if exists public.test_case;
drop table if exists public.test_case_history;
drop table if exists public.change_history cascade;
drop table if exists public.change cascade;
drop table if exists public.change_phase cascade;
drop table if exists public.change_type cascade;
drop table if exists public.epic_history cascade;
drop table if exists public.epic cascade;
drop table if exists public.project cascade;

create table public.project
(
    id       bigint generated by default as identity primary key not null,
    name     text                                   not null,
    last_ref int                      default 0     not null,
    created  timestamp with time zone default now() not null,
    modified timestamp with time zone default now() not null
);

create table public.epic
(
    id         bigint generated by default as identity primary key not null,
    version    smallint                 default 0     not null,
    project_id bigint                                 not null,
    name       text                                   not null,
    done_tc    smallint                 default 0     not null,
    total_tc   smallint                 default 0     not null,
    completed         smallint generated always as
        (coalesce((100 * done_tc / nullif(total_tc, 0))::smallint, 0)) stored,
    created    timestamp with time zone default now() not null,
    modified   timestamp with time zone default now() not null
);

create table public.epic_history
(
    id         bigint                   not null,
    version    smallint                 not null,
    project_id bigint                   not null,
    name       text                     not null,
    modified   timestamp with time zone not null,
    deleted    boolean default false    not null,
    primary key (id, version)
);

create table public.change_phase
(
    slug     text    default 'backlog' not null primary key,
    priority integer default 0         not null
);

create table public.change_type
(
    slug     text    default 'feature' not null primary key,
    priority integer default 0         not null
);

create table public.change
(
    id                bigint generated by default as identity primary key not null,
    ref               integer                  default 0               not null,
    version           smallint                 default 0               not null,
    slug              text                     default ''::text        not null,
    project_id        bigint                                           not null,
    change_phase      text                     default 'backlog'::text not null,
    change_types      text[]                                           not null,
    epic_id           bigint,
    title             text                                             not null,
    body  text,
    pr_body text,
    pr_url  text,
    agent_edit        boolean                  default false           not null,
    open              boolean                  default true            not null,
    done_tc           smallint                 default 0               not null,
    total_tc          smallint                 default 0               not null,
    completed         smallint generated always as (COALESCE(
            ((((100 * done_tc) / NULLIF(total_tc, 0)))::smallint)::integer, 0)) stored,
    created           timestamp with time zone default now()           not null,
    modified          timestamp with time zone default now()           not null
);

create table public.change_history
(
    id                bigint                   not null,
    version           smallint                 not null,
    project_id        bigint                   not null,
    change_types      text[]                   not null,
    epic_id           bigint,
    title             text                     not null,
    body  text,
    agent_edit        boolean                  not null,
    modified          timestamp with time zone not null,
    deleted           boolean default false    not null,
    primary key (id, version)
);

create table public.test_case
(
    id         bigint generated by default as identity
        primary key,
    version    smallint                 default 0     not null,
    change_id  bigint                                 not null,
    scenario   text                                   not null,
    done       boolean                  default false not null,
    created    timestamp with time zone default now() not null,
    modified   timestamp with time zone default now() not null
);

create table public.test_case_history
(
    id         bigint                   not null,
    version    smallint                 not null,
    change_id  bigint                                 not null,
    scenario text                     not null,
    modified   timestamp with time zone not null,
    deleted    boolean                  not null,
    primary key (id, version)
);

create view public.vw_project as
SELECT p.id,
       p.name,
       p.last_ref,
       p.created,
       p.modified,
       COALESCE(count(c.*), 0::bigint) AS change_count
FROM project p
         LEFT JOIN change c ON p.id = c.project_id
GROUP BY p.id, p.name, p.last_ref, p.created, p.modified
ORDER BY p.modified desc;

create view public.vw_epic as
SELECT e.id,
       e.version,
       e.project_id,
       e.name,
       e.done_tc,
       e.total_tc,
       e.completed,
       count(c.*)::integer AS change_count,
       e.created,
       e.modified
FROM epic e
         LEFT JOIN change c ON e.id = c.epic_id
GROUP BY e.id, e.version, e.project_id, e.name, e.done_tc, e.total_tc, e.completed, e.created, e.modified
ORDER BY e.project_id, e.name;

create view public.vw_change_list as
SELECT c.id,
       c.ref,
       c.slug,
       c.project_id,
       c.change_phase,
       c.change_types,
       c.epic_id,
       e.name AS epic_name,
       c.title,
       c.agent_edit,
       c.open,
       c.done_tc,
       c.total_tc,
       c.completed,
       c.modified
FROM change c
         LEFT JOIN epic e ON c.epic_id = e.id
ORDER BY c.project_id, c.modified DESC;

create view public.vw_change_details as
SELECT c.id,
       c.ref,
       c.version,
       c.slug,
       c.project_id,
       c.change_phase,
       c.change_types,
       c.epic_id,
       e.name AS epic_name,
       c.title,
       c.body,
       c.pr_body,
       c.pr_url,
       c.agent_edit,
       c.open,
       c.done_tc,
       c.total_tc,
       c.completed,
       c.created,
       c.modified
FROM change c
         LEFT JOIN epic e ON c.epic_id = e.id
ORDER BY c.project_id, c.modified DESC;

create view public.vw_foreign_key as
SELECT conname             AS foreign_key_name,
       conrelid::regclass  AS table_name,
       confrelid::regclass AS referenced_table
FROM pg_constraint
WHERE contype = 'f'::"char"
  AND connamespace = 'public'::regnamespace::oid
ORDER BY (conrelid::regclass), conname;

create procedure public.sp_epic_to_history(IN _id bigint, IN _deleted boolean)
    language plpgsql
as
$$
begin
    insert into public.epic_history (
        id, version, project_id, name, modified, deleted
    )
    select
        id, version, project_id, name, modified, _deleted
    from public.epic
    where id = _id;
end;
$$;

create procedure public.sp_change_to_history(IN _id bigint, IN _deleted boolean)
    language plpgsql
as
$$
begin
    insert into public.change_history (
        id, version, project_id, change_types, epic_id, title, body, agent_edit, modified, deleted
    )
    select
        id, version, project_id, change_types, epic_id, title, body, agent_edit, modified, _deleted
    from public.change
    where id = _id;
end;
$$;

create procedure public.sp_test_case_to_history(IN _id bigint, IN _deleted boolean)
    language plpgsql
as
$$
begin
    insert into public.test_case_history (
        id, version, change_id, scenario, modified, deleted
    )
    select
        id, version, change_id, scenario, modified, _deleted
    from public.test_case
    where id = _id;
end;
$$;

create procedure public.sp_epic_test_case_recalculate(IN _epic_id bigint)
    language plpgsql
as
$$
declare
    _done_tc smallint;
    _total_tc smallint;
begin
    if _epic_id is null then return; end if;

    select
        coalesce(sum(done_tc), 0),
        coalesce(sum(total_tc), 0)
    into
        _done_tc,
        _total_tc
    from public.change
    where epic_id=_epic_id;

    update public.epic
    set
        done_tc=_done_tc,
        total_tc=_total_tc
    where id=_epic_id;
end;
$$;

create procedure public.sp_change_test_case_recalculate(IN _change_id bigint)
    language plpgsql
as
$$
declare
    _epic_id bigint;
    _done_tc smallint;
    _total_tc smallint;
begin
    select count(*) into _done_tc from test_case where change_id=_change_id and done=true;
    select count(*) into _total_tc from test_case where change_id=_change_id;

    update public.change
    set
        done_tc=_done_tc,
        total_tc=_total_tc,
        modified=now()
    where id=_change_id;

    select epic_id into _epic_id from change where id=_change_id;
    call sp_epic_test_case_recalculate(_epic_id);
end;
$$;

create function public.fn_change_insert(_project_id bigint, _change_types text[], _epic_id bigint, _title text, _body text) returns bigint
    language plpgsql
as
$$
declare
    _ref int;
    _slug text;
    _id bigint;
begin
    update public.project set last_ref=last_ref+1 where id=_project_id returning last_ref into _ref;
    _title=regexp_replace(trim(_title), '\s+', ' ', 'g');
    _slug=regexp_replace(lower(_title), '\s+', '_', 'g');
    _slug=concat(lpad(_ref::text, 6, '0'), '-', _slug);

    insert into public.change (
        ref, slug, project_id, change_types, epic_id, title, body
    )
    values (
               _ref, _slug, _project_id, _change_types, _epic_id, _title, _body
           ) returning id into _id;

    return _id;
end;
$$;
